import './globals.css'
import { Raleway } from 'next/font/google'

const principal_font  = Raleway({subsets:["latin"]})

export const metadata = {
  title: 'Weather App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={principal_font}>{children}</body>
    </html>
  )
}
